(setenv "WOOF_COMPILER" "c:/my_system/src/misc/woof/trunk/woofc.exe")
(setenv "WOOF_MODULES" "c:/my_system/src/misc/woof/trunk/kernel")

(load "lib/sc2.scm")
(load "lib/comlist.scm")
(load "lib/srfi-1.scm")
(load "lib/vector.scm")
(load "lib/string.scm")
(load "lib/port-copying.scm")
(load "lib/test.scm")
(load "compiler.scm")
(load "woof-object.scm")
(load "machine-state.scm")
(load "continuations.scm")
(load "exception-handling.scm")
(load "function-calling.scm")
(load "instructions.scm")
(load "primitives.scm")
(load "machine.scm")
(load "test-compiler-and-machine.scm")

(run-woof-object-tests)
(run-machine-state-tests)
(run-function-calling-tests)
(run-machine-tests)
(run-compiler-and-machine-tests)